export const LIMITS = {
    FULL_NAME_LENGTH: 100,
    EMAIL_LENGTH: 255,
    PASSWORD_LENGTH: 128,
    LOFT_NAME_LENGTH: 100,
    LOFT_DESCRIPTION_LENGTH: 250,
    MESSAGE_CONTENT_LENGTH: 250,
    SEARCH_QUERY_LENGTH: 150,
};
